// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adffoemgfwszdktszaxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZmZvZW1nZndzemRrdHN6YXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTIyMjIsImV4cCI6MjA1NzcyODIyMn0.9xDPcuZQcukTjuVBQcZqwxcE3l-PRqEdrABaB_SYpT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);